### ISSUE TITLE
Incorrect info in quiz

### ISSUE THREAD

**Issue by will-chang6** [learn-co-curriculum/phase-3-quiz-object-inheritance#1]
### Canvas Link

https://learning.flatironschool.com/courses/6462/quizzes/48400

### Concern

Typo in question 2. 
The answer says "Yes! We use the less than symbol followed by the name of the parent class to specify that Laptop inherits from Computer."
It should be "Yes! We use the **parenthesis** followed by the name of the parent class to specify that Laptop inherits from Computer.

**Comment by lizbur10** [comment]
Hi @will-chang6 ! Thanks for posting this issue. Unfortunately, do to an error that was made when the quiz was created, this issue got posted to the wrong repo. We have corrected the error so I'm going to go ahead and close this issue. You can see the [correct repo with the correction made here](https://github.com/learn-co-curriculum/python-p3-quiz-object-inheritance). 💙
