### ISSUE TITLE
Object Inheritance Quiz Questions

### ISSUE THREAD

**Issue by ckelly38** [learn-co-curriculum/phase-3-quiz-object-inheritance#2]
### Canvas Link

https://learning.flatironschool.com/courses/6559/quizzes/47506

### Concern

Question 1:

TRUE*/FALSE/IDON'T KNOW: Object inheritance means that an object can use all of the attributes and behaviors (i.e. all of the methods) of the parent/super class.

*Although the answer selected to be correct is TRUE. Java, and JavaScript, among many others allow for private variables which in the parent class is not accessible to the children. So taken out of the context of the language being Python, the answer is **_actually FALSE_**.

Question 5:

"class Furniture:
  def build(self):
    print("Your furniture is being built")

We have a parent class Furniture and a subclass Table. In the Table class, we want to be able to call build() and have it print "You have chosen a table" followed by "Your furniture is being built". Which code block achieves this? Choose the best option.

1  I don't know.
  
2 class Table:
  def build(self):
    print("You have chosen a table")
    print("Your furniture is being built")
  
3 class Table(Furniture):
  def build(self):
    super().build()
    print("You have chosen a table")

  
4 class Table(Furniture):
  def build(self):
    print("You have chosen a table")
    print("Your furniture is being built")
  
5 class Table(Furniture):
  def build(self):
    print("You have chosen a table")
    super().build()"

Although option 5 was selected as the best answer, **best is relative.** It needs to be qualified a little bit. While not repeating yourself is good and code reuse is encouraged, is it the best in terms of efficiency. If it is already there in the definition, the interpreter does not have to do any extra work like the effort for an additional function call inside of a different file. Let us say the computer is really slow. In that case, the **best option would actually be 2.**

NOTE #s were not included in the options on the question itself. The question allows the user to assume that the __init__() is applied.

### Additional Context

Question #1 has the wrong answer because it is language dependent and the question was asked without providing a language.

Question #5 the options are relative and what is best is also relative so option 2 is better than 5 in terms of not having the computer do any extra work... but generally not repeating yourself is good too. Option 2 is easy to type out for a new developer... especially if they have not learned or do not understand how to use super() well... We actually do not need inheritance to solve the problem. Though if you enforce strictly requiring inheritance than 2 is eliminated. Clearly I eliminated option #1 does not solve the problem. I also eliminated option #3 because the order is wrong. Although option #4 is also a valid solution to the problem, it uses inheritance unnecessarily. **Which is best for what?** Since we do not need inheritance to solve the problem, 2 is better than 4 which is better than 5. If we rule out 2: then 4 is better than 5. If you think not repeating yourself is better then 5 is the best option.

An alternative approach to question 5 is sorting and searching algorithms: when the list is small n will win, but as it gets bigger, then there are other better approaches like nlog(n), with a really small list n^2 can be really fast, but as the list gets bigger, then n^2 takes a really long time. If you can have a constant sorting time, great! Long term that wins. Short term loses to n^2 and n. So again **which is best for what?**

### Suggested Changes

Question #1. **Requires the language of Python and other languages that do not distinguish between public and private** to be used for your answer to be correct; otherwise change the answer to **false**.

Question #5. **Requires more context** as to what is best for who? The programmer? The interpreter? Or even provide a better use case: where one would not want to copy and paste a ton of code....

**Comment by lizbur10** [comment]
Hi @ckelly38 ! Thanks for bringing these issues to our attention. Unfortunately, due to an error that was made when the quiz was created, this issue was posted to the wrong repo so I'm going to transfer it to the [correct repo](https://github.com/learn-co-curriculum/python-p3-quiz-object-inheritance/issues/1) and close it here. 💙
